//libs/constants/src/lib/conquest/core-data/names.ts

export const nameStructures = {
  Aarakocra: [
    {
      first: [
        'A',
        'Ca',
        'Da',
        'E',
        'Fa',
        'Ga',
        'Ha',
        'I',
        'Ja',
        'Ka',
        'La',
        'Ma',
        'Na',
        'O',
        'Pa',
        'Ra',
        'Sa',
        'Ta',
        'U',
        'Va',
        'Wa',
        'Xa',
        'Ya',
        'Za',
      ],
      second: ['ka', 'li', 'mo', 'nu', 'pi', 'ru', 'si', 'tu', 've'],
      third: ['an', 'bi', 'ka', 'lo', 'mi', 'na', 'ro', 'si', 'ta'],
    },
  ],
  Aasimar: [
    {
      first: [
        'Ae',
        'Ba',
        'Ce',
        'Di',
        'Eo',
        'Fa',
        'Gi',
        'He',
        'Io',
        'Je',
        'Ka',
        'Li',
        'Me',
        'Ni',
        'Oe',
        'Pa',
        'Re',
        'Si',
        'Te',
        'Ui',
        'Ve',
        'Wi',
        'Xi',
        'Ye',
        'Ze',
      ],
      second: ['ri', 'el', 'is', 'us', 'an'],
      third: ['el', 'ael', 'iel', 'uel', 'al'],
    },
  ],
  'Bugbear': [
    { first: ["Bra", "Dra", "Gra", "Kra", "Nra", "Pra", "Rra", "Tra", "Vra", "Zra"], 
      second: ["ag", "eg", "ig", "og", "ug"],
      third: ["ak", "ik", "ok", "uk", "yk"]
    }
  ],
  'Changeling': [
    { first: ["Al", "Be", "Ci", "Da", "Ef", "Go", "Hu", "Ir", "Jo", "Ki", "La", "Mo", "Ni", "Or", "Pa", "Qu", "Ro", "St", "Ta", "Ur", "Vi", "Wi", "Xa", "Ye", "Zu"], 
      second: ["an", "en", "in", "on", "un"],
      third: ["is", "us", "es", "os", "ys"]
    }
  ],
  Dragonborn: [
    {
      first: [
        'Arj',
        'Bal',
        'Cra',
        'Dra',
        'Eth',
        'Gor',
        'Har',
        'Ind',
        'Jal',
        'Kor',
        'Lar',
        'Mor',
        'Nor',
        'Oro',
        'Pru',
        'Qua',
        'Ras',
        'Sar',
        'Tur',
        'Uru',
        'Ver',
        'Wyr',
        'Xyr',
        'Yar',
        'Zor',
      ],
      second: [
        'han',
        'keth',
        'lidor',
        'myar',
        'nadar',
        'pax',
        'quar',
        'rith',
        'sark',
        'tiroth',
      ],
      third: ['', '', '', '', '', '', '', '', '', ''],
    },
  ],
  Dwarf: [
    {
      first: [
        'Ba',
        'Do',
        'Fi',
        'Gu',
        'He',
        'Ki',
        'Lo',
        'Mo',
        'Nu',
        'Og',
        'Pi',
        'Qu',
        'Ro',
        'Su',
        'To',
        'Ul',
        'Ve',
        'Wo',
        'Xa',
        'Yo',
        'Zu',
      ],
      second: [
        'var',
        'rik',
        'mor',
        'gin',
        'fel',
        'dur',
        'gar',
        'lak',
        'mor',
        'nur',
      ],
      third: ['', '', '', '', '', '', '', '', '', ''],
    },
  ],
  Elf: [
    {
      first: [
        'Ae',
        'Be',
        'De',
        'El',
        'Fa',
        'Jo',
        'Ki',
        'Li',
        'Na',
        'O',
        'Pa',
        'Re',
        'Si',
        'Ta',
        'Va',
      ],
      second: [
        'del',
        'far',
        'mor',
        'ther',
        'guin',
        'nir',
        'fir',
        'we',
        'lye',
        'ven',
      ],
      third: ['a', 'e', 'i', 'o', 'u', 'ia', 'ea', 'ara', 'ora'],
    },
  ],
  Firbolg: [
    {
      first: ['B', 'D', 'F', 'H', 'J', 'L', 'N', 'P', 'R', 'T', 'V', 'X', 'Z'],
      second: ['a', 'e', 'i', 'o', 'u'],
      third: ['rn', 'ld', 'm', 'll', 'rth', 'n', 'th', 'l', 'nn'],
    },
  ],
  Genasi: [
    {
      first: [
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        'G',
        'H',
        'I',
        'J',
        'K',
        'L',
        'M',
        'N',
        'O',
        'P',
        'Q',
        'R',
        'S',
        'T',
        'U',
        'V',
        'W',
        'X',
        'Y',
        'Z',
      ],
      second: ['a', 'e', 'i', 'o', 'u'],
      third: ['rth', 'st', 't', 'ph', 'nd', 'x', 'nt', 'm', 'l'],
    },
  ],
  Gith: [
    {
      first: ['G', 'K', 'N', 'R', 'S', 'Z'],
      second: ['a', 'e', 'i', 'o', 'u'],
      third: ['th', 'n', 'r', 'z', 'k'],
    },
  ],
  Gnome: [
    {
      first: [
        'Al',
        'Bu',
        'Ci',
        'Da',
        'El',
        'Fi',
        'Ga',
        'He',
        'Ib',
        'Jo',
        'Ki',
        'Lo',
        'Mi',
        'Nu',
        'Op',
        'Pi',
        'Qu',
        'Ro',
        'Si',
        'Te',
        'Ur',
        'Vi',
        'We',
        'Xo',
        'Ye',
        'Za',
      ],
      second: [
        'bwick',
        'dizzle',
        'fidget',
        'gimble',
        'hobble',
        'itch',
        'jumble',
        'krackle',
        'loll',
        'muddle',
        'nibble',
        'pocket',
        'quibble',
        'rattle',
        'sprocket',
        'twizzle',
        'umble',
        'vex',
        'wobble',
        'x',
        'yaffle',
        'zizzle',
      ],
      third: ['', '', '', '', '', '', '', '', '', ''],
    },
  ],
  Goliath: [
    {
      first: [
        'A',
        'Ba',
        'Ca',
        'Da',
        'E',
        'Fa',
        'Ga',
        'Ha',
        'I',
        'Ja',
        'Ka',
        'La',
        'Ma',
        'Na',
        'O',
        'Pa',
        'Ra',
        'Sa',
        'Ta',
        'U',
        'Va',
        'Wa',
        'Xa',
        'Ya',
        'Za',
      ],
      second: ['ka', 'lu', 'me', 'no', 'po', 'ra', 'si', 'tu', 've'],
      third: ['an', 'bin', 'kon', 'len', 'min', 'pon', 'run', 'sun', 'ton'],
    },
  ],
  'Half-Elf': [
    {
      first: [
        'Al',
        'Be',
        'Ce',
        'De',
        'Er',
        'Fi',
        'Ge',
        'Ha',
        'Il',
        'Jo',
        'Ke',
        'Li',
        'Ma',
        'No',
        'Ol',
        'Pe',
        'Qu',
        'Ro',
        'Sa',
        'Te',
        'Ul',
        'Va',
        'We',
        'Xa',
        'Yo',
        'Ze',
      ],
      second: [
        'dar',
        'bor',
        'fan',
        'dor',
        'han',
        'lam',
        'mor',
        'nor',
        'pom',
        'ror',
        'san',
        'shor',
        'tor',
        'vor',
      ],
      third: ['', '', '', '', '', '', '', '', '', ''],
    },
  ],
  'Half-Orc': [
    {
      first: [
        'Ba',
        'Do',
        'Gr',
        'Hr',
        'Kr',
        'Ma',
        'Ne',
        'Pr',
        'Ra',
        'Th',
        'Ur',
        'Zu',
      ],
      second: ['gar', 'mak', 'dor', 'gul', 'zod', 'mok', 'rok', 'tog', 'zug'],
      third: ['', '', '', '', '', '', '', '', ''],
    },
  ],
  Halfling: [
    {
      first: [
        'Ad',
        'Bi',
        'Ci',
        'Do',
        'Eg',
        'Fi',
        'Gi',
        'Hi',
        'Ig',
        'Jo',
        'Ki',
        'Lo',
        'Mi',
        'Ni',
        'Og',
        'Pi',
        'Qu',
        'Ro',
        'Si',
        'Ti',
        'Ug',
        'Vi',
        'Wi',
        'Xi',
        'Yo',
        'Zi',
      ],
      second: [
        'berry',
        'don',
        'fry',
        'gourd',
        'harp',
        'nip',
        'pickle',
        'quat',
        'rind',
        'sago',
        'tart',
        'umbs',
        'vine',
        'wort',
        'yam',
        'zest',
      ],
      third: ['', '', '', '', '', '', '', '', '', ''],
    },
  ],
  'Hobgoblin': [
    { first: ["Hob", "Job", "Kob", "Lob", "Mob", "Nob", "Pob", "Rob", "Sob", "Tob"], 
      second: ["ar", "er", "ir", "or", "ur"],
      third: ["din", "fin", "gin", "hin", "kin"]
    }
  ],
  Human: [
    {
      first: [
        'Al',
        'El',
        'Be',
        'De',
        'Ed',
        'Ha',
        'Jo',
        'Le',
        'Ma',
        'Re',
        'Sa',
        'Wi',
      ],
      second: [
        'bert',
        'ric',
        'nore',
        'son',
        'red',
        'mond',
        'net',
        'na',
        'la',
        'vin',
      ],
      third: ['', '', '', '', '', '', '', '', '', ''],
    },
  ],
  Kenku: [
    {
      first: [
        'Ch',
        'D',
        'Fr',
        'G',
        'H',
        'K',
        'L',
        'M',
        'N',
        'P',
        'R',
        'S',
        'T',
        'V',
        'W',
        'Z',
      ],
      second: ['irp', 'eep', 'ock', 'ip', 'eak', 'oop', 'ap', 'oop', 'eep'],
      third: ['', '', '', '', '', '', '', '', ''],
    },
  ],
  'Kobold': [
    { first: ["Ak", "Ek", "Ik", "Ok", "Uk", "Yk", "Bk", "Dk", "Fk", "Gk", "Hk", "Jk", "Kk", "Lk", "Mk", "Nk", "Pk", "Rk", "Sk", "Tk", "Vk", "Wk", "Xk", "Zk"], 
      second: ["ra", "re", "ri", "ro", "ru"],
      third: ["", "", "", "", ""]
    }
  ]
  Lizardfolk: [
    {
      first: [
        'Ss',
        'Ch',
        'Dr',
        'Ff',
        'Gh',
        'Hs',
        'Jh',
        'Kl',
        'Ll',
        'Mn',
        'Nh',
        'Pf',
        'Rh',
        'Sl',
        'Tl',
        'Vl',
        'Wh',
        'Xl',
        'Yl',
        'Zl',
      ],
      second: ['a', 'e', 'i', 'o', 'u'],
      third: ['rth', 'nt', 'st', 'x', 'ckt', 'ss', 'ff', 'll', 'zz'],
    },
  ],
  Tabaxi: [
    {
      first: [
        'Bright',
        'Dancing',
        'Echoing',
        'Falling',
        'Golden',
        'Hunting',
        'Jumping',
        'Kicking',
        'Leaping',
        'Mysterious',
        'Nimble',
        'Observant',
        'Prancing',
        'Quick',
        'Running',
        'Stealthy',
        'Tricky',
        'Unseen',
        'Vibrant',
        'Whispering',
        'Exotic',
        'Yawning',
        'Zipping',
      ],
      second: [
        'Creek',
        'Wind',
        'Flame',
        'Leaf',
        'Eagle',
        'Fox',
        'Hare',
        'Ibis',
        'Jaguar',
        'Kite',
        'Lynx',
        'Moth',
        'Night',
        'Owl',
        'Panther',
        'Quail',
        'Raccoon',
        'Snake',
        'Tiger',
        'Unicorn',
        'Vole',
        'Wolf',
        'Xenops',
        'Yak',
        'Zebra',
      ],
      third: ['', '', '', '', '', '', '', '', '', '', ''],
    },
  ],
  Tiefling: [
    {
      first: [
        'Ak',
        'Bar',
        'Car',
        'Dra',
        'Eku',
        'Fer',
        'Gol',
        'Her',
        'Ik',
        'Jas',
        'Kel',
        'Lor',
        'Mor',
        'Nik',
        'Oph',
        'Per',
        'Qar',
        'Ras',
        'Sho',
        'Tur',
        'Uvi',
        'Ver',
        'Wes',
        'Xav',
        'Yar',
        'Zep',
      ],
      second: [
        'menos',
        'thius',
        'morn',
        'canos',
        'dran',
        'halis',
        'seran',
        'deth',
        'phum',
      ],
      third: ['', '', '', '', '', '', '', '', ''],
    },
  ],
  Triton: [
    {
      first: [
        'Aqu',
        'Bris',
        'Cor',
        'Delp',
        'Ebb',
        'Fin',
        'Gill',
        'Har',
        'Isl',
        'Jet',
        'Kelp',
        'Lag',
        'Mael',
        'Ner',
        'Ocean',
        'Pel',
        'Quor',
        'Rip',
        'Sea',
        'Tid',
        'Urch',
        'Vort',
        'Wav',
        'Xer',
        'Yara',
        'Zost',
      ],
      second: [
        'us',
        'ion',
        'rin',
        'tide',
        'lun',
        'ruus',
        'shen',
        'tois',
        'zun',
      ],
      third: ['', '', '', '', '', '', '', '', ''],
    },
  ],
  'Warforged': [
    { first: ["Alpha", "Beta", "Gamma", "Delta", "Epsilon", "Zeta", "Eta", "Theta", "Iota", "Kappa", "Lambda", "Mu", "Nu", "Xi", "Omicron", "Pi", "Rho", "Sigma", "Tau", "Upsilon", "Phi", "Chi", "Psi", "Omega"], 
      second: ["-01", "-02", "-03", "-04", "-05", "-06", "-07", "-08", "-09", "-10"],
      third: ["", "", "", "", ""]
    }
  ],
  'Yuan-ti Pureblood': [
    {
      first: [
        'His',
        'Iss',
        'Jis',
        'Kis',
        'Lis',
        'Mis',
        'Nis',
        'Ois',
        'Pis',
        'Ris',
        'Sis',
        'Tis',
        'Vis',
        'Wis',
        'Xis',
        'Yis',
        'Zis',
      ],
      second: ['sa', 'se', 'si', 'so', 'su'],
      third: ['', '', '', '', ''],
    },
  ],
};
