import { Flute } from '@assets/sounds';
import { Roar } from '@assets/sounds';

export const themes = {
  light: {
    name: 'light',
    'primary-color': '#4CAF50',
    'secondary-color': '#8BC34A',
    'accent-color': '#A5D6A7',
    'bg-color': '#E8F5E9',
    'surface-color': '#C8E6C9',
    'text-color': '#333333',
    'text-on-primary-color': '#ffffff',
    'text-on-secondary-color': '#ffffff',
    'primary-icon-color': '#4a5568',
    'secondary-icon-color': '#FFD166',
    'success-color': '#81C784',
    'error-color': '#FF3B3B',
    'warning-color': '#FFAA00',
    'info-color': '#17A2B8',
    'border-color': '#DCEDC8',
    'hover-color': '#66BB6A',
    'active-color': '#43A047',
    'hover-secondary-color': '#9CCC65',
    'active-secondary-color': '#7CB342',
    'disabled-color': '#EDEDED',
    'sun-icon-color': '#FFD700',
    'moon-icon-color': '#C0C0C0',
    'bg-opacity-color': 'rgba(232, 245, 233, 0.6)',
    sound: Flute,
  },
  dark: {
    name: 'dark',
    'primary-color': '#FF0000',
    'secondary-color': '#8B0000',
    'accent-color': '#B22222',
    'bg-color': '#000000',
    'surface-color': '#1A1A1A',
    'text-color': '#E9E9E9',
    'text-on-primary-color': '#ffffff',
    'text-on-secondary-color': '#ffffff',
    'primary-icon-color': '#B5B5B5',
    'secondary-icon-color': '#FF6347',
    'success-color': '#3DB365',
    'error-color': '#FF5658',
    'warning-color': '#FF4500',
    'info-color': '#149BA6',
    'border-color': '#34383E',
    'hover-color': '#DC143C',
    'active-color': '#CD5C5C',
    'hover-secondary-color': '#A52A2A',
    'active-secondary-color': '#800000',
    'disabled-color': '#4A4A4A',
    'sun-icon-color': '#FFB640',
    'moon-icon-color': '#B0B0B0',
    'bg-opacity-color': 'rgba(0, 0, 0, 0.8)',
    sound: Roar,
  },
};
