export const themes = {
  light: {
    name: 'light',
    'primary-color': '#A8D5BA',
    'secondary-color': '#6A8D7F',
    'accent-color': '#B3E2C7',
    'bg-color': '#ffffff',
    'surface-color': '#F5F5F5',
    'text-color': '#000000',
    'text-on-primary-color': '#ffffff',
    'text-on-secondary-color': '#ffffff',
    'primary-fill': '#6A8D7F',
    'primary-stroke': '#6A8D7F',
    'secondary-fill': '#A0AEC0',
    'secondary-stroke': '#A0AEC0',
    'success-color': '#28A745',
    'error-color': '#DC3545',
    'warning-color': '#FFC107',
    'info-color': '#64B6AC',
    'border-color': '#EDEDED',
    'hover-color': '#E8E8E8',
    'active-color': '#C5C5C5',
    'hover-secondary-color': '#567970',
    'active-secondary-color': '#405D60',
    'disabled-color': '#EDEDED',
    'sun-icon-color': '#FFD700',
    'moon-icon-color': '#C0C0C0',
    'bg-opacity-color': 'rgba(255, 255, 255, 0.6)',
    sound: 'https://app-assets.vercel.app/sounds/air-swoosh.wav',
  },
  dark: {
    name: 'dark',
    'primary-color': '#f25626',
    'secondary-color': '#9DA3A8',
    'accent-color': '#ffffff',
    'bg-color': '#1a202c',
    'surface-color': '#3D3D3D',
    'text-color': '#e2e8f0',
    'text-on-primary-color': '#ffffff',
    'text-on-secondary-color': '#2a2f40',
    'primary-fill': '#e2e8f0',
    'primary-stroke': '#e2e8f0',
    'secondary-fill': '#5a6678',
    'secondary-stroke': '#5a6678',
    'success-color': '#55D68B',
    'error-color': '#F56565',
    'warning-color': '#FFD600',
    'info-color': '#3DB8E9',
    'border-color': '#414141',
    'hover-color': '#1D1D1D',
    'active-color': '#0E0E0E',
    'hover-secondary-color': '#8B9297',
    'active-secondary-color': '#72787D',
    'disabled-color': '#5B5B5B',
    'sun-icon-color': '#FFA700',
    'moon-icon-color': '#D3D3D3',
    'bg-opacity-color': 'rgba(26, 32, 44, 0.6)',
    sound: 'https://app-assets.vercel.app/sounds/air-swoosh.wav',
  },
};
