export const languages = [
  'Common',
  'Dwarvish',
  'Elvish',
  'Giant',
  'Gnomish',
  'Goblin',
  'Halfling',
  'Orc',
  'Abyssal',
  'Celestial',
  'Draconic',
  'Deep Speech',
  'Infernal',
  'Primordial',
  'Sylvan',
  'Undercommon',
  'Aquan',
  'Auran',
  'Ignan',
  'Terran',
  'Modron',
  'Slaad',
  'Gith',
  'Riedran',
  'Quori',
  'Kalashtar',
  'Thri-Kreen',
  'Bladeling',
  'Warforged',
  'Shifter',
  'Minotaur',
  'Kenku',
  'Tabaxi',
  'Triton',
  'Yuan-Ti',
  'Lizardfolk',
  'Necril',
  'Elemental',
  'Aarakocra',
  'Gnoll',
  'Vegepygmy',
  'Grell',
  'Sahuagin',
  'Umber Hulk',
  'Blink Dog',
  'Wight',
  'Balor',
  'Solar',
  'Mimic',
  'Treant',
  'Spritespeak',
  'Otyugh',
  'Myconid',
  'Hook Horror',
  'Loxodon',
  'Vedalken',
  'Simic',
  'Azorius',
  'Dimir',
  'Izzet',
  'Rakdos',
  'Golgari',
  'Gruul',
  'Boros',
  'Selesnya',
  'Orzhov',
  'Merfolk',
  'Kraken',
  'Troll',
  'Firbolg',
  'Grung',
  'Chitine',
  'Faerie',
  'Harpy',
  'Genie',
  'Mummy',
  'Worg',
  'Tengu',
  'Kobold',
  'Vedalken',
  'Ancient',
  'Doppleganger',
  'Banshee',
  'Boggle',
  'Oni',
  'Satyr',
  'Will-o’-Wisp',
  'Nymph',
  'Naga',
  'Pseudodragon',
  'Rakshasa',
  'Changeling',
  'Devil Sight',
  'Arcane',
  'Ethereal',
  'Titan',
  'Valkyrie',
  'Eldritch',
  'Sphinx',
  'Homunculus',
  'Phoenix',
  'Wyvern',
  'Displacer Beast',
  'Wendigo',
  'Cryptic',
  'Moon Elf',
  'Sun Elf',
  'Atlantean',
  'Vulcan',
  'Klingon',
  'Dothraki',
  'Valyrian',
  'Esperanto',
  'Kryptonian',
  'Na’vi',
  'Morse Code',
  'Sign Language',
];

export const specialTraits = [
  'spellcasting',
  'regeneration',
  'resistance to fire',
  'resistance to cold',
  'resistance to poison',
  'flight',
  'invisible',
  'shape shifting',
  'teleportation',
  'etherealness',
  'immunity to magic',
  'acidic touch',
  'poisonous bite',
  'petrification',
  'mind control',
  'web weaving',
  'water breathing',
  'burrowing',
  'phasing',
  'enhanced senses',
  'charm',
  'fear aura',
  'psychic powers',
  'mimicry',
  'resistance to necrotic damage',
  'resistance to radiant damage',
  'resistance to bludgeoning',
  'resistance to piercing',
  'resistance to slashing',
  'undead fortitude',
  'feral instincts',
  'time manipulation',
  'healing touch',
  'truesight',
  'darkvision',
  'blindsight',
  'tremorsense',
  'light generation',
  'illusion casting',
  'telekinesis',
  'energy drain',
  'elemental summoning',
  'resurrection',
  'invulnerability',
  'anti-magic field',
  'multiattack',
  'divination',
  'dimensional travel',
  'fire breathing',
  'ice breathing',
  'lightning bolt',
  'soul capture',
  'gravity manipulation',
  'negate invisibility',
  'swallowing',
  'fast healing',
  'sonic scream',
  'magic resistance',
  'detect thoughts',
  'berserk',
  'toxic spores',
  'incorporeal',
  'shadow stealth',
  'blood frenzy',
  'reflective carapace',
  'martial prowess',
  'weapon mastery',
  'intangibility',
  'smoke screen',
  'hive mind',
  'fungal body',
  'summon minions',
  'astral projection',
  'force field',
  'paralysis',
  'death touch',
  'rage',
  'size alteration',
  'disintegration',
  'electric shock',
  'magnetic field',
  'sandstorm',
  'tornado',
  'volcanic eruption',
  'reality warping',
  'necromancy',
  'vampirism',
  'lycanthropy',
  'plant growth',
  'aura of purity',
  'reincarnation',
  'chain lightning',
  'wish granting',
  'luck manipulation',
  'astral trapping',
  'dream invasion',
  'reality manipulation',
  'divine intervention',
  'possession',
  'shapeshifting into specific forms',
  'absorption',
  'curse inflicting',
  'retributive strike',
  'acid spray',
  'frostbite',
  'weapon conjuration',
  'alter self',
  'clone creation',
  'mind swap',
];

export const species = [
  'aberration',
  'beast',
  'celestial',
  'dragon',
  'elemental',
  'fey',
  'fiend',
  'giant',
  'monstrosity',
  'ooze',
  'plant',
  'undead',
  'human',
  'elf',
  'dwarf',
  'orc',
  'goblin',
  'troll',
  'nymph',
  'sprite',
  'gorgon',
  'chimera',
  'sphinx',
  'angel',
  'demon',
  'devil',
  'vampire',
  'werewolf',
  'merfolk',
  'harpy',
  'siren',
  'satyr',
  'minotaur',
  'centaur',
  'wraith',
  'banshee',
  'golem',
  'djinn',
  'lich',
  'naga',
  'salamander',
  'kobold',
  'gargoyle',
  'pixie',
  'imp',
  'homunculus',
  'treant',
  'dryad',
  'cyclops',
  'wyvern',
  'manticore',
  'hydra',
  'griffon',
  'roc',
  'pegasus',
  'basilisk',
  'kraken',
  'zombie',
  'skeleton',
  'ghost',
  'poltergeist',
  'specter',
  'shade',
  'revenant',
  'phantom',
  'eidolon',
  'genie',
  'ogre',
  'hobgoblin',
  'shapeshifter',
  'mimic',
  'fae',
  'seraphim',
  'valkyrie',
  'ghoul',
  'wight',
  'drake',
  'lich',
  'lamia',
  'hag',
  'archon',
  'daeva',
  'rakshasa',
  'brownie',
  'mephit',
  'boggle',
  'gremlin',
  'kelpie',
  'selkie',
  'barghest',
  'wendigo',
  'yeti',
  'mummy',
  'sasquatch',
  'nessie',
  'quasit',
  'xorn',
  'otyugh',
  'umber hulk',
  'ettercap',
  'darkmantle',
  'choker',
  'cloaker',
  'rust monster',
  'ankheg',
  'meenlock',
  'yeth hound',
  'grimlock',
  'myconid',
  'vegepygmy',
  'troglodyte',
  'lizardfolk',
  'kenku',
  'aranea',
  'bulette',
  'ankheg',
  'owlbear',
  'displacer beast',
  'carrion crawler',
  'bullywug',
  'piercer',
  'roper',
  'mimic',
  'ettercap',
  'phase spider',
  'grell',
  'hook horror',
  'cambion',
  'flumph',
  'yuan-ti',
  'quaggoth',
];

export const alignments = [
  'lawful good',
  'neutral good',
  'chaotic good',
  'lawful neutral',
  'true neutral',
  'chaotic neutral',
  'lawful evil',
  'neutral evil',
  'chaotic evil',
];
