// libs/constants/src/lib/dnd-data.ts

export const dndAbilityScores = ['STR', 'DEX', 'CON', 'INT', 'WIS', 'CHA'];

export const dndConditionTypes = [
  'Blinded',
  'Charmed',
  'Deafened',
  'Frightened',
  'Grappled',
  'Incapacitated',
  'Paralyzed',
  'Petrified',
  'Poisoned',
  'Prone',
  'Restrained',
  'Stunned',
  'Unconscious',
  'Exhaustion',
  'Bleeding',
  'Burning',
  'Frozen',
  'Cursed',
  'Enraged',
  'Entangled',
  'Invisible',
  'Silenced',
  'Slowed',
  'Weakened',
];

export const dndLootOptions = [
  'gold',
  'silver',
  'copper',
  'platinum',
  'electrum',
  'gems',
  'lint',
  'leaves',
  'jewelry',
  'artifacts',
  'scrolls',
  'potions',
  'weapons',
  'armor',
  'magic items',
  'maps',
  'books',
  'clothing',
  'food',
  'tools',
  'trinkets',
  'bones',
  'herbs',
  'spices',
  'pelts',
  'feathers',
  'shells',
  'teeth',
  'horns',
  'scales',
  'relics',
  'runes',
  'tapestries',
  'paintings',
  'statues',
  'furniture',
  'musical instruments',
  'wines',
  'ale',
  'spirits',
  'letters',
  'diaries',
  'blueprints',
  'seeds',
  'plants',
  'minerals',
  'ores',
  'crystals',
];

export const dndWeaponLootOptions = [
  'elvish engraving',
  'dwarven engraving',
  'orcish engraving',
  'dragonbone hilt',
  'jewel-encrusted pommel',
  'mithril blade',
  'adamantine edge',
  'runic inscriptions',
  'celestial motifs',
  'infernal motifs',
  'feathered decoration',
  'leather-wrapped grip',
  'ivory inlays',
  'obsidian blade',
  'silvered edge',
  'gold detailing',
  'enchanted glow',
  'ghostly aura',
  'flaming enchantment',
  'frost-covered',
  'thunderous resonance',
  'poisoned coating',
  'blood groove',
  'double-edged',
  'serrated edge',
  'hooked tip',
  'barbed wire wrap',
  'crystal-infused',
  'shadowy essence',
  'ethereal transparency',
  'gnomish gadgetry',
  'halfling craftsmanship',
];

export const dndQuadrantOptions = [0, 1, 2, 3];
export const dndInteractableOptions = [true, false];
