// libs/constants/src/lib/language-data.ts

export const adjectives = [
  'colorful',
  'magnificent',
  'impressive',
  'elegant',
  'charming',
  'majestic',
  'stunning',
  'enchanting',
  'glamorous',
  'sophisticated',
  'unique',
  'exquisite',
  'spectacular',
  'fascinating',
  'alluring',
  'mesmerizing',
  'captivating',
  'breathtaking',
  'dazzling',
  'radiant',
  'shimmering',
  'sparkling',
  'brilliant',
  'gorgeous',
  'luxurious',
  'opulent',
  'sumptuous',
  'ornate',
  'regal',
  'resplendent',
];

export const connectingWords = [
  'with',
  'that has',
  'featuring',
  'boasting',
  'displaying',
  'showcasing',
  'highlighting',
  'exhibiting',
  'presenting',
  'revealing',
  'flaunting',
  'embodying',
  'incorporating',
  'combining',
  'integrating',
  'infused with',
  'adorned with',
  'accentuated by',
  'enhanced by',
  'enriched by',
  'graced with',
  'radiating',
  'oozing',
  'emanating',
  'overflowing with',
  'imbued with',
  'imbued with the spirit of',
  'imbued with the essence of',
  'imbued with the magic of',
];

export const descriptors = ['fast', 'slow', 'strong', 'weak'];
