export type MapConstant = {
  encounterObjectives: Array<{ objective: string; weight: number }>;
  mapSizes: Array<{ size: string; width: number; length: number }>;
  terrainTypes: Array<{ name: string }>;
  timeOfDay: Array<{ name: string; weight: number }>;
  weather: Array<{ name: string; weight: number }>;
  weatherChange: Array<{ name: string }>;
  weatherSeverity: Array<{ name: string; weight: number }>;
  weatherType: Array<{ name: string }>;
};

export const mapConstants: MapConstant = {
  encounterObjectives: [
    { objective: 'Capture the Flag (/ Hold flag for 2 rounds)', weight: 3 },
    { objective: 'Cleanse the Area of Enemies', weight: 3 },
    { objective: 'Defend this Location', weight: 1 },
    { objective: 'Defend this Object', weight: 1 },
    { objective: 'Defend this NPC', weight: 1 },
    {
      objective: 'Obtain the Item (at Object, Opposition searching for it)',
      weight: 3,
    },

    { objective: 'Rescue the Target', weight: 3 },
  ],
  mapSizes: [
    { size: 'Small (100ft x 100ft)', width: 100, length: 100 },
    { size: 'Medium (300ft x 300ft)', width: 300, length: 300 },
    { size: 'Large (500ft x 500ft)', width: 500, length: 500 },
    { size: 'Huge (700ft x 700ft)', width: 700, length: 700 },
    { size: 'Gargantuan (900ft x 900ft)', width: 900, length: 900 },
  ],
  terrainTypes: [
    { name: 'Alpine Lake' },
    { name: 'Arctic' },
    { name: 'Artesian Spring' },
    { name: 'Badlands' },
    { name: 'Barren' },
    { name: 'Bay' },
    { name: 'Bayou' },
    { name: 'Beach' },
    { name: 'Bog' },
    { name: 'Caldera' },
    { name: 'Canals' },
    { name: 'Canyon' },
    { name: 'Caves' },
    { name: 'Cliffs' },
    { name: 'Crater' },
    { name: 'Desert' },
    { name: 'Dry Lake Bed' },
    { name: 'Dunes' },
    { name: 'Estuary' },
    { name: 'Farmland' },
    { name: 'Fault' },
    { name: 'Fields' },
    { name: 'Fissured' },
    { name: 'Fjords' },
    { name: 'Forest' },
    { name: 'Geysers' },
    { name: 'Glacier' },
    { name: 'Grassland' },
    { name: 'Harbor' },
    { name: 'Hills' },
    { name: 'Hot Spring' },
    { name: 'Ice Sheet' },
    { name: 'Island' },
    { name: 'Jungle' },
    { name: 'Kelp Bed' },
    { name: 'Lake' },
    { name: 'Lava Field' },
    { name: 'Lava Tube' },
    { name: 'Marsh' },
    { name: 'Meadow' },
    { name: 'Mine' },
    { name: 'Mountain' },
    { name: 'Nettles & Brambles' },
    { name: 'Oasis' },
    { name: 'Ocean' },
    { name: 'Orchard' },
    { name: 'Permafrost' },
    { name: 'Plains' },
    { name: 'Plateau' },
    { name: 'Pond' },
    { name: 'Prairie' },
    { name: 'Quicksand' },
    { name: 'Rain Forest' },
    { name: 'Rapids' },
    { name: 'Reef' },
    { name: 'River' },
    { name: 'River Delta' },
    { name: 'Rocky' },
    { name: 'Sand Dunes' },
    { name: 'Sandbar' },
    { name: 'Savannah' },
    { name: 'Scrubland' },
    { name: 'Seaside' },
    { name: 'Sewers' },
    { name: 'Shallow Sea' },
    { name: 'Sink Hole' },
    { name: 'Spring' },
    { name: 'Strip Mine' },
    { name: 'Swamp' },
    { name: 'Taiga (Snow Forest)' },
    { name: 'Tide Pool' },
    { name: 'Tropical Island' },
    { name: 'Tundra' },
    { name: 'Tunnels' },
    { name: 'Underground' },
    { name: 'Underground Sea' },
    { name: 'Valley' },
    { name: 'Vineyard' },
    { name: 'Volcanic' },
    { name: 'Volcanic Island' },
    { name: 'Wastelands' },
    { name: 'Waterfalls' },
    { name: 'Wetlands' },
    { name: 'Wildlands' },
    { name: 'Wind Blasted' },
    { name: 'Floating Island' },
    { name: 'Colosseum' },
    { name: 'Pirate Ships' },
    { name: 'Moving Train' },
  ],
  timeOfDay: [
    { name: 'Night', weight: 8 },
    { name: 'Dawn', weight: 2 },
    { name: 'Day', weight: 12 },
    { name: 'Dusk', weight: 1 },
  ],
  weather: [
    { name: 'Yes', weight: 1 },
    { name: 'No', weight: 2 },
  ],
  weatherChange: [
    { name: 'Getting Worse' },
    { name: 'No Change' },
    { name: 'Getting Better' },
  ],
  weatherSeverity: [
    { name: 'Light', weight: 6 },
    { name: 'Normal', weight: 10 },
    { name: 'Severe', weight: 3 },
    { name: 'Extreme', weight: 1 },
  ],
  weatherType: [
    { name: 'Acid Rain' },
    { name: 'Blizzard' },
    { name: 'Cloudy' },
    { name: 'Cyclone' },
    { name: 'Drought' },
    { name: 'Flash Flood' },
    { name: 'Fog' },
    { name: 'Hailstorm' },
    { name: 'Hurricane' },
    { name: 'Monsoon' },
    { name: 'Rain' },
    { name: 'Sandstorm' },
    { name: 'Snownado' },
    { name: 'Thunderstorm' },
    { name: 'Tidal Wave' },
    { name: 'Tornado' },
    { name: 'Wildfire' },
    { name: 'Cold Temps' },
    { name: 'Hot Temps' },
  ],
};
