// libs/icons/feather/src/lib/useIcon.tsx

import {
  activityIcon,
  airplayIcon,
  alignJustifyIcon,
  alignLeftIcon,
  alignRightIcon,
  anchorIcon,
  apertureIcon,
  archiveIcon,
  arrowDownIcon,
  arrowLeftIcon,
  arrowRightIcon,
  arrowUpIcon,
  atSignIcon,
  awardIcon,
  barChartIcon,
  barChart2Icon,
  batteryIcon,
  bellIcon,
  bluetoothIcon,
  boldIcon,
  bookIcon,
  bookmarkIcon,
  boxIcon,
  briefcaseIcon,
  calendarIcon,
  cameraIcon,
  castIcon,
  checkCircleIcon,
  checkSquareIcon,
  clipboardIcon,
  clockIcon,
  cloudIcon,
  codeIcon,
  codepenIcon,
  commandIcon,
  compassIcon,
  copyIcon,
  cornerDownLeftIcon,
  cornerDownRightIcon,
  cornerUpLeftIcon,
  cornerUpRightIcon,
  cpuIcon,
  creditCardIcon,
  cropIcon,
  crosshairIcon,
  databaseIcon,
  deletedIcon,
  discIcon,
  divideCircleIcon,
  divideSquareIcon,
  divideIcon,
  dollarSignIcon,
  downloadCloudIcon,
  downloadIcon,
  dribbbleIcon,
  driveIcon,
  dropletIcon,
  edit2Icon,
  edit3Icon,
  editIcon,
  externalLinkIcon,
  eyeOffIcon,
  eyeIcon,
  earIcon,
  ejectIcon,
  facebookIcon,
  fastForwardIcon,
  featherIcon,
  figmaIcon,
  fileMinusIcon,
  filePlusIcon,
  fileTextIcon,
  fileIcon,
  filmIcon,
  filterIcon,
  flagIcon,
  folderMinusIcon,
  folderPlusIcon,
  folderIcon,
  framerIcon,
  frownIcon,
  giftIcon,
  gitBranchIcon,
  gitCommitIcon,
  gitMergeIcon,
  gitPullRequestIcon,
  githubIcon,
  gitlabIcon,
  globeIcon,
  gridIcon,
  hardDriveIcon,
  hashIcon,
  headphonesIcon,
  heartIcon,
  helpCircleIcon,
  hexagonIcon,
  homeIcon,
  imageIcon,
  inboxIcon,
  infoIcon,
  instagramIcon,
  italicIcon,
  keyIcon,
  layersIcon,
  layoutIcon,
  lifeBuoyIcon,
  link2Icon,
  linkIcon,
  linkedinIcon,
  listIcon,
  loaderIcon,
  lockIcon,
  logInIcon,
  logOutIcon,
  mailIcon,
  mapPinIcon,
  mapIcon,
  maximize2Icon,
  maximizeIcon,
  mehIcon,
  menuIcon,
  messageCircleIcon,
  messageSquareIcon,
  micOffIcon,
  micIcon,
  minimize2Icon,
  minimizeIcon,
  minusCircleIcon,
  minusSquareIcon,
  minusIcon,
  monitorIcon,
  moonIcon,
  moreHorizontalIcon,
  moreVerticalIcon,
  mousePointerIcon,
  moveIcon,
  musicIcon,
  navigation2Icon,
  navigationIcon,
  octagonIcon,
  // packageIcon,
  paperclipIcon,
  pauseCircleIcon,
  pauseIcon,
  penToolIcon,
  percentIcon,
  phoneCallIcon,
  phoneForwardedIcon,
  phoneIncomingIcon,
  phoneMissedIcon,
  phoneOffIcon,
  phoneOutgoingIcon,
  phoneIcon,
  pieChartIcon,
  playCircleIcon,
  playIcon,
  plusCircleIcon,
  plusSquareIcon,
  plusIcon,
  pocketIcon,
  powerIcon,
  printerIcon,
  radioIcon,
  refreshCcwIcon,
  refreshCwIcon,
  repeatIcon,
  rewindIcon,
  rotateCcwIcon,
  rotateCwIcon,
  rssIcon,
  saveIcon,
  scissorsIcon,
  searchIcon,
  sendIcon,
  serverIcon,
  settingsIcon,
  share2Icon,
  shareIcon,
  shieldOffIcon,
  shieldIcon,
  shoppingBagIcon,
  shoppingCartIcon,
  shuffleIcon,
  sidebarIcon,
  skipBackIcon,
  skipForwardIcon,
  slackIcon,
  slashIcon,
  slidersIcon,
  smartphoneIcon,
  smileIcon,
  speakerIcon,
  squareIcon,
  starIcon,
  stopCircleIcon,
  sunIcon,
  sunriseIcon,
  sunsetIcon,
  tabletIcon,
  tagIcon,
  targetIcon,
  terminalIcon,
  thermometerIcon,
  thumbsDownIcon,
  thumbsUpIcon,
  toggleLeftIcon,
  toggleRightIcon,
  toolIcon,
  trash2Icon,
  trashIcon,
  trelloIcon,
  trendingDownIcon,
  trendingUpIcon,
  triangleIcon,
  truckIcon,
  tvIcon,
  twitchIcon,
  twitterIcon,
  typeIcon,
  umbrellaIcon,
  underlineIcon,
  unlockIcon,
  uploadCloudIcon,
  uploadIcon,
  userCheckIcon,
  userMinusIcon,
  userPlusIcon,
  userXIcon,
  userIcon,
  usersIcon,
  videoOffIcon,
  videoIcon,
  voicemailIcon,
  volume1Icon,
  volume2Icon,
  volumeXIcon,
  volumeIcon,
  watchIcon,
  wifiOffIcon,
  wifiIcon,
  windIcon,
  xCircleIcon,
  xOctagonIcon,
  xSquareIcon,
  xIcon,
  youtubeIcon,
  zapOffIcon,
  zapIcon,
  zoomInIcon,
  zoomOutIcon,
} from '../data/featherIcons';

const iconMap: { [key: string]: string } = {
  activity: activityIcon,
  airplay: airplayIcon,
  alignJustify: alignJustifyIcon,
  alignLeft: alignLeftIcon,
  alignRight: alignRightIcon,
  anchor: anchorIcon,
  aperture: apertureIcon,
  archive: archiveIcon,
  arrowDown: arrowDownIcon,
  arrowLeft: arrowLeftIcon,
  arrowRight: arrowRightIcon,
  arrowUp: arrowUpIcon,
  atSign: atSignIcon,
  award: awardIcon,
  barChart: barChartIcon,
  barChart2: barChart2Icon,
  battery: batteryIcon,
  bell: bellIcon,
  bluetooth: bluetoothIcon,
  bold: boldIcon,
  book: bookIcon,
  bookmark: bookmarkIcon,
  box: boxIcon,
  briefcase: briefcaseIcon,
  calendar: calendarIcon,
  camera: cameraIcon,
  cast: castIcon,
  checkCircle: checkCircleIcon,
  checkSquare: checkSquareIcon,
  clipboard: clipboardIcon,
  clock: clockIcon,
  cloud: cloudIcon,
  code: codeIcon,
  codepen: codepenIcon,
  command: commandIcon,
  compass: compassIcon,
  copy: copyIcon,
  cornerDownLeft: cornerDownLeftIcon,
  cornerDownRight: cornerDownRightIcon,
  cornerUpLeft: cornerUpLeftIcon,
  cornerUpRight: cornerUpRightIcon,
  cpu: cpuIcon,
  creditCard: creditCardIcon,
  crop: cropIcon,
  crosshair: crosshairIcon,
  database: databaseIcon,
  deleted: deletedIcon,
  disc: discIcon,
  dollarSign: dollarSignIcon,
  downloadCloud: downloadCloudIcon,
  download: downloadIcon,
  dribbble: dribbbleIcon,
  droplet: dropletIcon,
  ear: earIcon,
  edit2: edit2Icon,
  edit3: edit3Icon,
  edit: editIcon,
  eject: ejectIcon,
  externalLink: externalLinkIcon,
  eyeOff: eyeOffIcon,
  eye: eyeIcon,
  facebook: facebookIcon,
  fastForward: fastForwardIcon,
  feather: featherIcon,
  figma: figmaIcon,
  fileMinus: fileMinusIcon,
  filePlus: filePlusIcon,
  fileText: fileTextIcon,
  file: fileIcon,
  film: filmIcon,
  filter: filterIcon,
  flag: flagIcon,
  folderMinus: folderMinusIcon,
  folderPlus: folderPlusIcon,
  folder: folderIcon,
  framer: framerIcon,
  frown: frownIcon,
  gift: giftIcon,
  gitBranch: gitBranchIcon,
  gitCommit: gitCommitIcon,
  gitMerge: gitMergeIcon,
  gitPullRequest: gitPullRequestIcon,
  github: githubIcon,
  gitlab: gitlabIcon,
  globe: globeIcon,
  grid: gridIcon,
  hardDrive: hardDriveIcon,
  hash: hashIcon,
  helpCircle: helpCircleIcon,
  headphones: headphonesIcon,
  heart: heartIcon,
  hexagon: hexagonIcon,
  home: homeIcon,
  image: imageIcon,
  inbox: inboxIcon,
  info: infoIcon,
  instagram: instagramIcon,
  italic: italicIcon,
  key: keyIcon,
  layers: layersIcon,
  layout: layoutIcon,
  lifeBuoy: lifeBuoyIcon,
  link2: link2Icon,
  link: linkIcon,
  linkedin: linkedinIcon,
  list: listIcon,
  loader: loaderIcon,
  lock: lockIcon,
  logIn: logInIcon,
  logOut: logOutIcon,
  mail: mailIcon,
  mapPin: mapPinIcon,
  map: mapIcon,
  maximize2: maximize2Icon,
  maximize: maximizeIcon,
  meh: mehIcon,
  menu: menuIcon,
  messageCircle: messageCircleIcon,
  messageSquare: messageSquareIcon,
  micOff: micOffIcon,
  mic: micIcon,
  minimize2: minimize2Icon,
  minimize: minimizeIcon,
  minusCircle: minusCircleIcon,
  minusSquare: minusSquareIcon,
  minus: minusIcon,
  monitor: monitorIcon,
  moon: moonIcon,
  moreHorizontal: moreHorizontalIcon,
  moreVertical: moreVerticalIcon,
  mousePointer: mousePointerIcon,
  move: moveIcon,
  music: musicIcon,
  navigation2: navigation2Icon,
  navigation: navigationIcon,
  octagon: octagonIcon,
  // package: packageIcon,
  paperclip: paperclipIcon,
  pauseCircle: pauseCircleIcon,
  pause: pauseIcon,
  penTool: penToolIcon,
  percent: percentIcon,
  phoneCall: phoneCallIcon,
  phoneForwarded: phoneForwardedIcon,
  phoneIncoming: phoneIncomingIcon,
  phoneMissed: phoneMissedIcon,
  phoneOff: phoneOffIcon,
  phoneOutgoing: phoneOutgoingIcon,
  phone: phoneIcon,
  pieChart: pieChartIcon,
  playCircle: playCircleIcon,
  play: playIcon,
  plusCircle: plusCircleIcon,
  plusSquare: plusSquareIcon,
  plus: plusIcon,
  pocket: pocketIcon,
  power: powerIcon,
  printer: printerIcon,
  radio: radioIcon,
  refreshCcw: refreshCcwIcon,
  refreshCw: refreshCwIcon,
  repeat: repeatIcon,
  rewind: rewindIcon,
  rotateCcw: rotateCcwIcon,
  rotateCw: rotateCwIcon,
  rss: rssIcon,
  save: saveIcon,
  scissors: scissorsIcon,
  search: searchIcon,
  send: sendIcon,
  server: serverIcon,
  settings: settingsIcon,
  share2: share2Icon,
  share: shareIcon,
  shieldOff: shieldOffIcon,
  shield: shieldIcon,
  shoppingBag: shoppingBagIcon,
  shoppingCart: shoppingCartIcon,
  shuffle: shuffleIcon,
  sidebar: sidebarIcon,
  skipBack: skipBackIcon,
  skipForward: skipForwardIcon,
  slack: slackIcon,
  slash: slashIcon,
  sliders: slidersIcon,
  smartphone: smartphoneIcon,
  smile: smileIcon,
  speaker: speakerIcon,
  square: squareIcon,
  star: starIcon,
  stopCircle: stopCircleIcon,
  sun: sunIcon,
  sunrise: sunriseIcon,
  sunset: sunsetIcon,
  tablet: tabletIcon,
  tag: tagIcon,
  target: targetIcon,
  terminal: terminalIcon,
  thermometer: thermometerIcon,
  thumbsDown: thumbsDownIcon,
  thumbsUp: thumbsUpIcon,
  toggleLeft: toggleLeftIcon,
  toggleRight: toggleRightIcon,
  tool: toolIcon,
  trash2: trash2Icon,
  trash: trashIcon,
  trello: trelloIcon,
  trendingDown: trendingDownIcon,
  trendingUp: trendingUpIcon,
  triangle: triangleIcon,
  truck: truckIcon,
  tv: tvIcon,
  twitch: twitchIcon,
  twitter: twitterIcon,
  type: typeIcon,
  umbrella: umbrellaIcon,
  underline: underlineIcon,
  unlock: unlockIcon,
  uploadCloud: uploadCloudIcon,
  upload: uploadIcon,
  userCheck: userCheckIcon,
  userMinus: userMinusIcon,
  userPlus: userPlusIcon,
  userX: userXIcon,
  user: userIcon,
  users: usersIcon,
  videoOff: videoOffIcon,
  video: videoIcon,
  voicemail: voicemailIcon,
  volume1: volume1Icon,
  volume2: volume2Icon,
  volumeX: volumeXIcon,
  volume: volumeIcon,
  watch: watchIcon,
  wifiOff: wifiOffIcon,
  wifi: wifiIcon,
  wind: windIcon,
  xCircle: xCircleIcon,
  xOctagon: xOctagonIcon,
  xSquare: xSquareIcon,
  x: xIcon,
  youtube: youtubeIcon,
  zapOff: zapOffIcon,
  zap: zapIcon,
  zoomIn: zoomInIcon,
  zoomOut: zoomOutIcon,
};

export const useIcon = (iconName: string) => {
  return iconMap[iconName] || null;
};
