import generateRandomItem from '../utils/generateRandomItem.js';

export const Items = [
  { name: 'shard of obsidian', type: 'item', value: 10 },
  { name: 'rope necklace', type: 'item', value: 5 },
  { name: 'tiny component pouch', type: 'item', value: 25 },
  { name: 'backpack', type: 'item', value: 2 },
  { name: 'serpent venom', type: 'poison', value: 200 },
  { name: 'boots of the winterlands', type: 'magical item', value: 2500 },
  { name: 'shawm', type: 'item', value: 2 },
  { name: 'shield', type: 'armor', value: 10 },
  { name: 'petrified mouse', type: 'item', value: 5 },
  { name: 'glowing satchel', type: 'item', value: 50 },
  { name: 'light hammer', type: 'weapon', value: 2 },
  { name: 'dragonchess set', type: 'item', value: 10 },
  { name: 'deed for a parcel of land', type: 'item', value: 100 },
  { name: '1-inch cube', type: 'item', value: 1 },
  { name: 'handaxe', type: 'weapon', value: 5 },
  { name: 'quarterstaff', type: 'weapon', value: 2 },
  { name: 'silver snuffbox', type: 'item', value: 25 },
  { name: 'parchment', type: 'item', value: 1 },
  {
    name: 'deed for a parcel of land (unknown realm)',
    type: 'item',
    value: 100,
  },
  { name: 'component pouch', type: 'item', value: 25 },
  { name: 'glass orb', type: 'item', value: 20 },
  { name: 'iron spikes', type: 'item', value: 1 },

  { name: 'longsword', type: 'weapon', value: 15 },
  { name: 'shortsword', type: 'weapon', value: 10 },
  { name: 'mace', type: 'weapon', value: 5 },
  { name: 'battleaxe', type: 'weapon', value: 10 },
  { name: 'rapier', type: 'weapon', value: 25 },

  { name: 'leather armor', type: 'armor', value: 10 },
  { name: 'chain shirt', type: 'armor', value: 50 },
  { name: 'scale mail', type: 'armor', value: 50 },
  { name: 'plate armor', type: 'armor', value: 1500 },

  { name: 'cloak of protection', type: 'magical item', value: 2000 },
  { name: 'lockpicks', type: 'tools', value: 25 },
  { name: 'crowbar', type: 'tools', value: 2 },
  { name: 'hammer', type: 'tools', value: 1 },
  { name: 'grappling hook', type: 'tools', value: 2 },
  { name: 'flint and steel', type: 'tools', value: 1 },
  { name: 'ruby', type: 'gems', value: 100 },
  { name: 'sapphire', type: 'gems', value: 100 },
  { name: 'emerald', type: 'gems', value: 100 },
  { name: 'diamond', type: 'gems', value: 500 },
  { name: 'moonstone', type: 'stones', value: 50 },
  { name: 'sunstone', type: 'stones', value: 50 },
  { name: 'bloodstone', type: 'stones', value: 25 },
  { name: 'agate', type: 'stones', value: 10 },
  { name: 'iron ore', type: 'ore', value: 2 },
  { name: 'silver ore', type: 'ore', value: 5 },
  { name: 'gold ore', type: 'ore', value: 25 },
  { name: 'mithril ore', type: 'ore', value: 100 },
  { name: 'wooden chest', type: 'containers', value: 10 },
  { name: 'ironbound chest', type: 'containers', value: 25 },
  { name: 'barrel', type: 'containers', value: 2 },
  { name: 'pouch', type: 'containers', value: 1 },
  { name: 'gold ring', type: 'jewelry', value: 25 },
  { name: 'silver necklace', type: 'jewelry', value: 50 },
  { name: 'pearl earrings', type: 'jewelry', value: 100 },
  { name: 'jade bracelet', type: 'jewelry', value: 75 },
  { name: 'scroll of fireball', type: 'scrolls', value: 150 },
  { name: 'scroll of healing word', type: 'scrolls', value: 50 },
  { name: 'scroll of invisibility', type: 'scrolls', value: 100 },
  { name: 'scroll of teleportation', type: 'scrolls', value: 200 },
  { name: 'spellbook', type: 'books', value: 50 },
  { name: 'book of lore', type: 'books', value: 25 },
  { name: 'atlas of the known world', type: 'books', value: 100 },
  { name: 'bestiary', type: 'books', value: 75 },
  { name: 'blueprint of a castle', type: 'blueprint', value: 500 },
  { name: 'blueprint of a ship', type: 'blueprint', value: 250 },
  { name: 'blueprint of a siege weapon', type: 'blueprint', value: 100 },
  { name: 'blueprint of a hidden passage', type: 'blueprint', value: 150 },

  { name: 'recipe for a healing potion', type: 'recipe', value: 50 },
  { name: 'recipe for a poison', type: 'recipe', value: 100 },
  { name: 'recipe for an alchemical concoction', type: 'recipe', value: 75 },
  { name: 'recipe for a magic-infused meal', type: 'recipe', value: 25 },

  { name: 'treasure map to a hidden hoard', type: 'treasure map', value: 100 },
  { name: 'treasure map to a sunken ship', type: 'treasure map', value: 150 },
  { name: 'treasure map to a dragons lair', type: 'treasure map', value: 200 },
  { name: 'treasure map to a lost city', type: 'treasure map', value: 250 },

  { name: 'ration pack', type: 'food', value: 1 },
  { name: 'trail mix', type: 'food', value: 1 },
  { name: 'dried fruit', type: 'food', value: 1 },
  { name: 'loaf of bread', type: 'food', value: 1 },
  { name: 'bottle of wine', type: 'food', value: 5 },
  { name: 'wedge of cheese', type: 'food', value: 2 },
  { name: 'jar of honey', type: 'food', value: 3 },
  { name: 'salted meat', type: 'food', value: 2 },
];

export const FullItems = Items.map(({ name, type, value }) =>
  generateRandomItem(name, type, value)
);
