export const Structures = [
  'lighthouse',
  'boulder',
  'abandoned castle',
  'bandit camp',
  'barren wasteland',
  'blacksmith shop',
  'bridge',
  'caravan',
  'cave',
  'city walls',
  'cliffside fortress',
  'crypt',
  'dam',
  'dark forest',
  'desert oasis',
  'dungeon',
  'dwarven mine',
  'elven treehouse',
  'farm',
  'fishing village',
  'fort',
  'goblin cave',
  'goblin fortress',
  'goblin village',
  'graveyard',
  'guild hall',
  'hidden temple',
  'hobbit hole',
  'inn',
  'keep',
  'library',
  'mansion',
  'marketplace',
  'mine',
  'monastery',
  'mountain pass',
  'necropolis',
  'oasis',
  'orc camp',
  'orc stronghold',
  'palace',
  'pirate hideout',
  'prison',
  'ruined temple',
  'shipwreck',
  'smugglers den',
  'stronghold',
  'tavern',
  'temple',
  'troll cave',
  'troll fortress',
  'village',
  'watchtower',
  'wizards tower',
];
