// libs/constants/src/tools.ts
export const TOOL_NAMES = [
  'JavaScript',
  'Vue.js',
  'Firebase',
  'SEO',
  'GitHub',
  'Pinia',
  'Express.js',
  'Node.js',
  'HTML5',
  'CSS3',
  'React.js',
  'Next.js',
  'Jest',
  'TailwindCSS',
  'Nx Monorepo',
  'WordPress',
  'Bootstrap',
  'SASS',
  'Git',
  'jQuery',
  'React Testing Library',
  'CLI',
  'CORESense',
  'Storybook',
  'TypeScript',
  'Vercel',
  'Stripe',
];

export const TOOL_LINKS = TOOL_NAMES.map((tool) => ({
  title: tool,
  link: `https://example.com/${tool.toLowerCase()}`,
}));
