export const themes = {
  light: {
    name: 'light',
    'primary-color': '#ff3e00',
    'secondary-color': '#A2A2A2',
    'accent-color': '#5AC8FA',
    'bg-color': '#FFFFFF',
    'secondary-bg-color': '#EFEFEF',
    'contact-button-color': '#5AC8FA',
    'surface-color': '#F7F7F7',
    'text-color': '#1D1D1F',
    'text-on-primary-color': '#FFFFFF',
    'text-on-secondary-color': '#FFFFFF',
    'primary-fill': '#4a5568',
    'primary-stroke': '#4a5568',
    'secondary-fill': '#A2A2A2',
    'secondary-stroke': '#A2A2A2',
    'menu-icon-color': '#007AFF',
    'success-color': '#34C759',
    'error-color': '#FF3B30',
    'warning-color': '#FF9500',
    'info-color': '#5AC8FA',
    'border-color': '#D1D1D1',
    'hover-color': '#E5E5EA',
    'active-color': '#C7C7CC',
    'hover-secondary-color': '#BFBFBF',
    'active-secondary-color': '#B1B1B1',
    'disabled-color': '#E0E0E0',
    'sun-icon-color': '#FFD60A',
    'moon-icon-color': '#636366',
    'bg-opacity-color': 'rgba(255, 255, 255, 0.6)',
    'dialog-bg-color': '#FFFFFF',
    'backdrop-color': '#F0F0F0',
    'gradient-color': '#EFEFEF',
    sound: 'https://app-assets.vercel.app/sounds/light_switch.wav',
    'shadow-color': 'rgba(0, 0, 0, 0.2)',
    'skeleton-base-color': '#d0d0d0',
    'skeleton-shine-color': '255, 255, 255',
  },
  dark: {
    name: 'dark',
    'primary-color': '#FFFFFF',
    'secondary-color': '#636366',
    'accent-color': '#ff3e00',
    'bg-color': '#000000',
    'secondary-bg-color': '#2C2C2E',
    'contact-button-color': '#ff3e00',
    'surface-color': '#1C1C1E',
    'text-color': '#FFFFFF',
    'text-on-primary-color': '#000000',
    'text-on-secondary-color': '#FFFFFF',
    'primary-fill': '#ff3e00',
    'primary-stroke': '#ff3e00',
    'secondary-fill': '#FFFFFF',
    'secondary-stroke': '#FFFFFF',
    'menu-icon-color': '#5AC8FA',
    'success-color': '#34C759',
    'error-color': '#FF3B30',
    'warning-color': '#FF9500',
    'info-color': '#007AFF',
    'border-color': '#545b6c',
    'hover-color': '#2C2C2E',
    'active-color': '#3A3A3C',
    'hover-secondary-color': '#48484A',
    'active-secondary-color': '#545b6c',
    'disabled-color': '#3F3F3F',
    'sun-icon-color': '#FFD60A',
    'moon-icon-color': '#8E8E93',
    'bg-opacity-color': 'rgba(0, 0, 0, 0.8)',
    'gradient-color': '#545b6c',
    sound: 'https://app-assets.vercel.app/sounds/robot-heartbeat.wav',
    'dialog-bg-color': '#1C1C1E',
    'backdrop-color': '#2C2C2E',
    'shadow-color': 'rgba(255, 255, 255, 0.1)',
    'skeleton-base-color': '#3A3A3C',
    'skeleton-shine-color': '255, 255, 255',
  },
};
