export const themes = {
  light: {
    name: 'light',
    'primary-color': '#35469c',
    'secondary-color': '#292929',
    'accent-color': '#ff3e00',
    'bg-color': '#FFFFFF',
    'surface-color': '#F0F0F0',
    'text-color': '#000000',
    'text-on-primary-color': '#FFFFFF',
    'text-on-secondary-color': '#FFFFFF',
    'text-on-accent-color': '#FFFFFF',
    'primary-icon-color': '#ff3e00',
    'secondary-icon-color': '#35469c',
    'success-color': '#008000',
    'error-color': '#FF0000',
    'warning-color': '#FFA500',
    'info-color': '#0000FF',
    'border-color': '#D0D0D0',
    'hover-color': '#ddd',
    'active-color': '#ccc',
    'hover-secondary-color': '#4c5261',
    'active-secondary-color': '#43485c',
    'disabled-color': '#e0e0e0',
    'sun-icon-color': '#FFD700',
    'moon-icon-color': '#808080',
    'bg-opacity-color': 'rgba(255, 255, 255, 0.6)',
    sound:
      'https://rshogan.imgix.net/projects/rshogancom/sounds/rshogancom_flick_switch.wav',
    'dialog-bg-color': '#FFFFFF',
    'backdrop-color': '#F0F0F0',
    'gradient-color': '#6fa3ef',
  },
  dark: {
    name: 'dark',
    'primary-color': '#e47461',
    'secondary-color': '#545b6c',
    'accent-color': '#292929',
    'bg-color': '#292929',
    'surface-color': '#1E1E1E',
    'text-color': '#FFFFFF',
    'text-on-primary-color': '#FFFFFF',
    'text-on-secondary-color': '#000000',
    'primary-icon-color': '#D4D4D4',
    'secondary-icon-color': '#e47461',
    'success-color': '#00FF00',
    'error-color': '#FF0000',
    'warning-color': '#FFA500',
    'info-color': '#1E90FF',
    'border-color': '#545b6c',
    'hover-color': '#43485c',
    'active-color': '#4c5261',
    'hover-secondary-color': '#545b6c',
    'active-secondary-color': '#4c5261',
    'disabled-color': '#3F3F3F',
    'sun-icon-color': '#FFD700',
    'moon-icon-color': '#808080',
    'bg-opacity-color': 'rgba(41, 41, 41, 0.8)',
    'gradient-color': '#545b6c',
    sound:
      'https://rshogan.imgix.net/projects/rshogancom/sounds/rshogancom_whooshdarkhissy.wav',
    'dialog-bg-color': '#292929',
    'backdrop-color': '#1E1E1E',
  },
};
