//themes.ts
export const themes = {
  light: {
    name: 'light',
    'primary-color': '#A8D5BA', // A light, pastel green for freshness and positivity
    'secondary-color': '#6A8D7F', // A muted teal for a noble look
    'accent-color': '#B3E2C7', // A light sage to complement the primary and secondary colors
    'bg-color': '#ffffff',
    'surface-color': '#F5F5F5',
    'text-color': '#000000',
    'text-on-primary-color': '#ffffff',
    'text-on-secondary-color': '#ffffff',
    'primary-fill': '#6A8D7F',
    'primary-stroke': '#6A8D7F',
    'secondary-fill': '#A0AEC0', // Softened to a cooler gray to balance the teals and greens
    'secondary-stroke': '#A0AEC0',
    'success-color': '#28A745',
    'error-color': '#DC3545',
    'warning-color': '#FFC107',
    'info-color': '#64B6AC', // Adjusted to a green-blue to sync with the theme
    'border-color': '#EDEDED',
    'hover-color': '#E8E8E8',
    'active-color': '#C5C5C5',
    'hover-secondary-color': '#567970',
    'active-secondary-color': '#405D60',
    'disabled-color': '#EDEDED',
    'sun-icon-color': '#FFD700',
    'moon-icon-color': '#C0C0C0',
    'bg-opacity-color': 'rgba(255, 255, 255, 0.6)',
    sound: 'https://app-assets.vercel.app/sounds/air-swoosh.wav',
  },
  dark: {
    name: 'dark',
    'primary-color': '#4B3621',
    'secondary-color': '#736357',
    'accent-color': '#DAA520',
    'bg-color': '#1a202c',
    'surface-color': '#2C2C2C',
    'text-color': '#E4E4E4',
    'text-on-primary-color': '#ffffff',
    'text-on-secondary-color': '#ffffff',
    'primary-fill': '#DAA520',
    'primary-stroke': '#DAA520',
    'secondary-fill': '#ACA9A3',
    'secondary-stroke': '#ACA9A3',
    'success-color': '#228B22',
    'error-color': '#B22222',
    'warning-color': '#FFD700',
    'info-color': '#3DB8E9',
    'border-color': '#403F3F',
    'hover-color': '#333333',
    'active-color': '#222222',
    'hover-secondary-color': '#8B9297',
    'active-secondary-color': '#72787D',
    'disabled-color': '#5B5B5B',
    'sun-icon-color': '#FFA700',
    'moon-icon-color': '#D3D3D3',
    'bg-opacity-color': 'rgba(26, 32, 44, 0.85)',
    sound: 'https://app-assets.vercel.app/sounds/air-swoosh.wav',
  },
};
