//themes.ts
export const themes = {
  light: {
    name: 'light',
    'primary-color': '#FFD700',
    'secondary-color': '#E0E0E0',
    'accent-color': '#C0C0C0',
    'bg-color': '#ffffff',
    'surface-color': '#F8F8F8',
    'text-color': '#333333',
    'text-on-primary-color': '#ffffff',
    'text-on-secondary-color': '#1A1A1A',
    'primary-fill': '#F0E68C',
    'primary-stroke': '#F0E68C',
    'secondary-fill': '#F5F5F5',
    'secondary-stroke': '#EDEDED',
    'success-color': '#32CD32',
    'error-color': '#FF6347',
    'warning-color': '#FFD700',
    'info-color': '#4682B4',
    'border-color': '#DDDDDD',
    'hover-color': '#EEEEEE',
    'active-color': '#CCCCCC',
    'hover-secondary-color': '#FFFFFF',
    'active-secondary-color': '#E5E5E5',
    'disabled-color': '#F0F0F0',
    'sun-icon-color': '#FFD700',
    'moon-icon-color': '#C0C0C0',
    'bg-opacity-color': 'rgba(255, 255, 255, 0.9)',
    sound: 'https://app-assets.vercel.app/sounds/air-swoosh.wav',
  },
  dark: {
    name: 'dark',
    'primary-color': '#4B3621',
    'secondary-color': '#736357',
    'accent-color': '#DAA520',
    'bg-color': '#1a202c',
    'surface-color': '#2C2C2C',
    'text-color': '#E4E4E4',
    'text-on-primary-color': '#ffffff',
    'text-on-secondary-color': '#ffffff',
    'primary-fill': '#DAA520',
    'primary-stroke': '#DAA520',
    'secondary-fill': '#ACA9A3',
    'secondary-stroke': '#ACA9A3',
    'success-color': '#228B22',
    'error-color': '#B22222',
    'warning-color': '#FFD700',
    'info-color': '#3DB8E9',
    'border-color': '#403F3F',
    'hover-color': '#333333',
    'active-color': '#222222',
    'hover-secondary-color': '#8B9297',
    'active-secondary-color': '#72787D',
    'disabled-color': '#5B5B5B',
    'sun-icon-color': '#FFA700',
    'moon-icon-color': '#D3D3D3',
    'bg-opacity-color': 'rgba(26, 32, 44, 0.85)',
    sound: 'https://app-assets.vercel.app/sounds/air-swoosh.wav',
  },
};
