import './global.css';
import { Inter } from 'next/font/google';
import { FloatingFooter } from '@with-nx/react-ui';

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Welcome to swapi-cards',
  description: 'Generated by create-nx-workspace',
};

// Loaded as an HTML <link> (not a CSS @import in global.css) because
// Turbopack drops a CSS @import that isn't the first rule in the final
// bundle -- see the neighboring @config directive. Same fix as
// apps/jhogancom/pages/_document.tsx's GoogleFontLoader, but built
// inline since Poller One + Roboto Flex's multi-axis query string
// (`opsz,wght@...`) doesn't fit GoogleFontLoader's single-weight-list
// URL builder.
const CUSTOM_FONTS_URL =
  'https://fonts.googleapis.com/css2?family=Poller+One&family=Roboto+Flex:opsz,wght@8..144,300;8..144,600;8..144,1000&display=swap';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link rel="stylesheet" href={CUSTOM_FONTS_URL} />
      </head>
      <body>
        {children}
        <FloatingFooter currentApp="swapi-cards" />
      </body>
    </html>
  );
}
