import './styles/global.css';
import { AuthProvider } from './contexts/AuthContext';

export const metadata = {
  title: 'Home | Conquest',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </AuthProvider>
  );
}
