type ActionType =
  | 'Action'
  | 'Bonus Action'
  | 'Lair Action'
  | 'Legendary Action'
  | 'Passive'
  | 'Reaction';

interface Ability {
  type: ActionType;
  name: string;
}

const data: { [key in ActionType]: string[] } = {
  Action: [
    'Adrenal Surge',
    'Breath Weapons',
    'Chain Sweep',
    'Charge',
    'Collapse Distance',
    'Creeping Darkness',
    'Death Ray',
    'Demonic Weapon',
    'Ethereal Stride',
    'Explosive Bolt',
    'Fiendish Charm',
    'Flurry of Claws',
    'Forgetfulness',
    'Freezing Strikes',
    'Glimpse the Temporal Flood',
    'Grave Bolts',
    'Harpoon',
    'Haste',
    'Head butt',
    'Howling Babble',
    'Ice Spear',
    'Iron Fist',
    'Life Drain',
    'Longbow',
    'Longsword',
    'Mind Blast',
    'Raise Ghoul',
    'Shield Bash',
    'Spit Slime',
    'Sudden Rush',
    'Superior Invisibility',
    'Tail',
    'Teleport',
    'Temporal Strike',
    'Thunderclap',
    'Trap Soul',
    'Unarmed Strike',
    'Unerring Slam',
    'Wail',
    'Warleaders Helix',
    'Weird Insight',
    'Whirlwind',
  ],
  'Bonus Action': [
    "Archer's Eye",
    'Divine Eminence',
    'Earth-Shaking Movement',
    'Fey Step',
    'Invisibility Field',
    "Lolth's Fickle Favor",
    'Paralysis',
    'Shadow Blend',
    'Shadow Step',
    'Superior Invisibility',
  ],
  'Lair Action': ['TO DO'],
  'Legendary Action': [
    'Break Concentration',
    'Cast a Spell',
    'Cold Burst',
    'Creeping Death',
    'Deadly Leap',
    'Ferocious Roar',
    'Freeze',
    'Stunning Wave',
    'Swat Away',
    'Teleport',
  ],
  Passive: [
    'Aberrant Quickness',
    'Alien Mind',
    'Annulment',
    'Antimagic Cone',
    'Antimagic Shell',
    'Army Arcana',
    'Aura of Annihilation',
    'Aura of Hopelessness',
    'Blind Rage',
    'Blood Frenzy',
    'Bloodfrenzy',
    'Bloodlust',
    'Blurred Movement',
    'Burning Fury',
    'Chameleon Carapace',
    'Chaotic Resonance',
    'Confer Fire Resistance',
    'Confusing Gaze',
    'Coordinated Attack',
    "Dark One's Own Luck",
    'Deal of a Lifetime',
    'Deathless',
    "Devil's Sight",
    'Dimensional Lock',
    'Discern Lie',
    'Displacement',
    'Disruptive Cacophony',
    'Elemental Demise',
    'Empowered Spell',
    'Esoteric Theft',
    'False Appearance',
    'Faultless Tracker',
    'Feed on Fire',
    'Feeding Frenzy',
    'Fire Absorption',
    'Fluxbending Overcast',
    "Gruumsh's Fury",
    'Heart of the Mummy Lord',
    'Infernal Despair',
    'Life Hunger',
    'Limited Magic Immunity',
    'Living Shadow',
    'Locus of the Firemind',
    'Master Chemister',
    'Master of the Grave',
    'Metal Immunity',
    'Mind Screen',
    'Multiple Heads',
    'Negative Energy Cone',
    'Overdraw',
    'Pacifying Presence',
    'Petrifying Gaze',
    'Phalanx Formation',
    'Poison Splash',
    'Precise Aim',
    'Protector',
    'Psychic Defense',
    'Reactive',
    'Reflective Carapace',
    'Regeneration',
    'Rejuvenation',
    'Skewer',
    'Slimy Hide',
    'Soul Thirst',
    'Spell Storing',
    'Spiked Bone Armor',
    'Suppress Magic',
    'Survivor',
    'Thrives on Company',
    'Transposition',
    'Tree Stride',
    'Undead Fortitude',
    'Unholy Aura',
    'Unstoppable',
    'Vulnerability to Wind',
    'War Magic',
    'Weapon Master',
    'Wild Mage',
    'Wounded Fury',
    'Yip',
  ],
  Reaction: [
    'Counterattack',
    'Feed on Weakness',
    'Misty Escape',
    'Precognitive Insight',
    'Reversal of Fortune',
    'Scouring Instruction',
    'Slippery',
    'Spell Leech',
    'Spell Reflection',
    'Spell Vitalization',
    'Sticky Shield',
    'Unbridled Fury',
    'Vicious Reprisal',
  ],
};

export default data;
